name: Update SEC Data

on:
  schedule:
    # Runs at minute 0 past every hour on weekdays (Monday through Friday)
    - cron: '0 * * * 1-5' 
  workflow_dispatch: # This adds a button allowing you to run it manually

jobs:
  fetch-and-deploy:
    runs-on: ubuntu-latest
    
    # We need to explicitly grant write permissions to push the data.json file
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Fetch Latest 10-Qs
        run: python fetch.py
        
      - name: Commit and Push Changes
        run: |
          # Set up git to commit as a bot
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Add the newly created data.json file
          git add data.json
          
          # If there are changes, commit and push them; otherwise, do nothing and exit successfully
          git commit -m "Auto-update latest 10-Q data" || exit 0
          git push
